### ISSUE TITLE
Strapdown.js domain

### ISSUE THREAD

**Issue by aitchdot** [chuckhoupt/autoindex_strapdown#2]
You'll run into errors trying to use themes, as .gif files are not available anymore

**Comment by aitchdot** [comment]
Where do i find the .gifs

**Comment by chuckhoupt** [comment]
Thanks for catching this. I see that `strapdownjs.com` no longer exists. I've fixed the live site at https://ais.habilis.net to use its own copy of strapdownjs and I'll commit the fixes to the repo soon.

**Comment by chuckhoupt** [comment]
I've update the repo and live site, so I'll close this issue. Let me know if you see other problems.
